# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/commit.yaml
---
name: "build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: "Run CI checks on Linux"
    runs-on: ubuntu-latest
    container: golang:1.16  # match go.mod version
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: "Init on first use"
        run: make init

      - name: "Run checks"
        run: make check

  test:
    name: "Run unit tests on Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: "Init on first use"
        run: make init

      - name: "Prefetch latest envoy"
        run: go run cmd/getenvoy/main.go fetch standard:1.17.1

      - name: "Run tests"
        run: make test.ci GO_TEST_EXTRA_OPTS="-timeout 60s"

      - name: "Generate coverage report"
        run: make coverage GO_COVERAGE_EXTRA_OPTS="-p 1"

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/coverage

  bin:
    name: "Build `getenvoy` and `e2e` binaries for use in e2e tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: "Init on first use"
        run: make init

      - name: "Build `getenvoy` and `e2e` binaries"
        run: make bin

      - name: "Share `getenvoy` and `e2e` binaries with the downstream jobs"
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: build/bin

  e2e_linux:
    name: "Run e2e tests on Linux"
    needs:
      - bin
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Re-use `getenvoy` and `e2e` binaries pre-built by the upstream job"
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: build/bin

      - name: "Build language-specific Docker build images"
        run: make builders

      - name: "Run e2e tests using `getenvoy` and `e2e` binaries built by the upstream job"
        run: ./ci/e2e/linux/run_tests.sh

  e2e_macos:
    name: "Run e2e tests on MacOS"
    needs:
      - bin
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Re-use `getenvoy` and `e2e` binaries pre-built by the upstream job"
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: build/bin

      - name: "Install 'Docker for Mac' (an older version that can be installed in CI environment)"
        run: ./ci/e2e/macos/install_docker.sh

      - name: "Build language-specific Docker build images"
        env:
          # don't use `DOCKER_BUILDKIT=1`, `--build-arg BUILDKIT_INLINE_CACHE=1` and `--cache-from`
          # options when using `Docker for Mac` in CI environment
          USE_DOCKER_BUILDKIT_CACHE: 'no'
        run: make builders

      - name: "Run e2e tests using `getenvoy` and `e2e` binaries built by the upstream job"
        run: ./ci/e2e/macos/run_tests.sh
